name: Check for PHP Warnings and Errors
on: 
  push:
      branches:
        - master
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: michaelw90/PHP-Lint@master
