name: Deploy to Webserver
on: 
  push:
      branches:
        - master
jobs:

  deploy:
    name: Deploy to Webserver
    runs-on: ubuntu-latest
    steps:
    - name: executing remote code pull over ssh using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: /root/update.sh
 
