name: Docker Build
on: 
  push:
      branches:
        - master
jobs:

  build_web:
    name: Build Webserver
    runs-on: ubuntu-latest
    steps:
    - name: executing remote docker build over ssh using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: /root/update.sh
 
